version: '3'
services:
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    depends_on:
      - db
        # condition: service_healthy
      - redis
        # condition: service_started
      - sidekiq
        # condition: service_started
  sidekiq:
    build: .
    env_file:
      - ".env"
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
          test: "pg_isready --username=postgres && psql --username=postgres --list"
          timeout: 10s
          retries: 20
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
