version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
      - sidekiq
  sidekiq:
    build: .
    env_file:
      - ".env"
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file:
      - ".env"
    volumes:
      - "${LOCAL_POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
  redis:
    image: "redis:alpine"
    volumes:
      - "${LOCAL_REDIS_DATA_DIR}:/var/lib/redis/data"

volumes:
  postgres_data:
