
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] { 'postgres'} %>
  password: <%= ENV['POSTGRES_PASSWORD'] { 'password' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { '5432' } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  database: <%= ENV['POSTGRES_DB'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { '5' } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST'] %>

production:
  <<: *default
  database: payments_production

