
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres'} %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { '5432' } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'payments_development' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { '5' } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB_TEST') { 'payments_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB_TEST') { 'payments_production' } %>
